/**
 * ES 物件API
 * （株）いい生活 が提供予定の 物件情報API のインターフェイス仕様書  いい物件Oneに登録した賃貸物件情報を参照する物件参照API仕様について定める。  ※1: 開発中のため、実際のリリース時の仕様は異なる場合がございます。  ※2: 売買物件に関する仕様に関してはα版であり、今後大きな仕様の見直しを行う可能性がございます。  ## リソース仕様  ### 通信仕様  HTTP/2 および HTTP/1.1 をサポートする。通信はTLSで暗号化されたHTTPSのみを許可する。  ### リクエストヘッダ  リクエストヘッダには以下の指定を必須とする。  | No. | リクエストヘッダのフィールド名 | 指定値 | |:---:|:-------------------------------|:-------| | 1 | Accept | application/json | | 2 | X-Api-Key | 弊社が指定するキー。ご利用のお客様を特定するためのもの。 |  Acceptヘッダには、常にapplication/json を指定する。 これにより、レスポンスがJSONであることを指示する。  ### データフォーマットと文字コード  データフォーマットはJSON、文字コードはUTF-8とする。  ### データ型  通常のJSONの型以外に擬似型としていくつかのデータ型を用意している。 これは、JSON標準では表現しきれないデータや、不動産特有のデータを扱うために定義したもので使用する。 また、ここに記載の無いデータ型については、 OpenAPI Specification (Version 3.0.2) の DataTypes に準拠する。  * [DataTypes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types)   | No. | 型 | 説明 | |:---:|:---|:-----| | 1 | string | JSON標準の文字列 | | 2 | int | JSON標準の整数 | | 3 | float | JSON標準の浮動小数点数 | | 4 | bool | JSON標準の真偽値 | | 5 | datetime | ISO8611フォーマットの日付時刻を表す文字列。YYYY-MM-DDTHH:MM:SS。 <br> 例: 2015-08-26T19:16:03 = 2015年8月26日19時16分03秒 | | 6 | date | ISO8611フォーマットの日付を表す文字列。YYYY-MM-DD。 <br> 例: 2015-08-26 = 2015年8月26日 | | 7 | datejun | 後述 |  #### datejun型  いい生活独自の日付と旬を表すフォーマット。YYYYMMJDD。  * YYYY: 西暦年 * MM: 月。01～12。ただし00とすることにより、年単位までの精度の数字を表現可能。 * J: 旬。1=上旬、2=中旬、3=下旬。 0とすることで月単位までの精度の数字を表現可能。 * DD: 日。01～31。ただし00とすることにより、旬単位までの精度の数字を表現可能。日単位の精度の場合、1～10日までは旬を1、11～20日までは旬を2、21日以降は旬を3と指定する必要がある。 * 例:     * 201900000 = 2019年     * 201901000 = 2019年1月     * 201903100 = 2019年3月上旬     * 201912300 = 2019年12月下旬     * 201906105 = 2019年6月5日     * 201908216 = 2019年8月16日  ## 検索パラメータ  ### OR 検索  パラメータタイプが `array` のキーについては、クエリパラメータで複数指定を行った場合、 指定された値のいずれかに一致する対象を検索する（ OR 検索）。  ex) `?layout_type_code=1&layout_type_code=2`  ### ソート順  `*.order` という名前のパラメータでソート順を指定可能。ascを指定したとき昇順、descを指定したとき降順となる。  ex) `?price.order=desc`  基本的にソート順は一つだけ指定する。 
 *
 * The version of the OpenAPI document: 6.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AreaWithMeasurementMethod from './AreaWithMeasurementMethod';
import BuildingFeature from './BuildingFeature';
import DateJun from './DateJun';
import FacingRoad from './FacingRoad';
import UseDistrict from './UseDistrict';

/**
 * The Building model module.
 * @module model/Building
 * @version 6.1.3
 */
class Building {
    /**
     * Constructs a new <code>Building</code>.
     * 建物
     * @alias module:model/Building
     * @param modified {Date} 
     * @param buildingName {String} 
     * @param buildingTypeCode {Number} 1: マンション<br/>2: リゾートマンション<br/>3: アパート<br/>4: テラスハウス<br/>5: タウンハウス<br/>6: 戸建<br/>7: 土地<br/>8: 店舗<br/>9: 事務所<br/>10: ビル<br/>11: 倉庫<br/>12: 工場<br/>13: トランクルーム<br/>14: 駐車場<br/>15: バイク置き場<br/>16: その他
     * @param prefecture {String} 
     * @param city {String} 
     * @param town {String} 
     * @param tyoume {String} 
     */
    constructor(modified, buildingName, buildingTypeCode, prefecture, city, town, tyoume) { 
        
        Building.initialize(this, modified, buildingName, buildingTypeCode, prefecture, city, town, tyoume);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, modified, buildingName, buildingTypeCode, prefecture, city, town, tyoume) { 
        obj['modified'] = modified;
        obj['building_name'] = buildingName;
        obj['building_type_code'] = buildingTypeCode;
        obj['prefecture'] = prefecture;
        obj['city'] = city;
        obj['town'] = town;
        obj['tyoume'] = tyoume;
    }

    /**
     * Constructs a <code>Building</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Building} obj Optional instance to populate.
     * @return {module:model/Building} The populated <code>Building</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Building();

            if (data.hasOwnProperty('building_guid')) {
                obj['building_guid'] = ApiClient.convertToType(data['building_guid'], 'String');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('building_name')) {
                obj['building_name'] = ApiClient.convertToType(data['building_name'], 'String');
            }
            if (data.hasOwnProperty('building_furigana')) {
                obj['building_furigana'] = ApiClient.convertToType(data['building_furigana'], 'String');
            }
            if (data.hasOwnProperty('total_units')) {
                obj['total_units'] = ApiClient.convertToType(data['total_units'], 'Number');
            }
            if (data.hasOwnProperty('building_class')) {
                obj['building_class'] = ApiClient.convertToType(data['building_class'], 'String');
            }
            if (data.hasOwnProperty('building_class_code')) {
                obj['building_class_code'] = ApiClient.convertToType(data['building_class_code'], 'Number');
            }
            if (data.hasOwnProperty('building_type')) {
                obj['building_type'] = ApiClient.convertToType(data['building_type'], 'String');
            }
            if (data.hasOwnProperty('building_type_code')) {
                obj['building_type_code'] = ApiClient.convertToType(data['building_type_code'], 'Number');
            }
            if (data.hasOwnProperty('total_floors')) {
                obj['total_floors'] = ApiClient.convertToType(data['total_floors'], 'Number');
            }
            if (data.hasOwnProperty('ground_floors')) {
                obj['ground_floors'] = ApiClient.convertToType(data['ground_floors'], 'Number');
            }
            if (data.hasOwnProperty('basement_floors')) {
                obj['basement_floors'] = ApiClient.convertToType(data['basement_floors'], 'Number');
            }
            if (data.hasOwnProperty('setback')) {
                obj['setback'] = ApiClient.convertToType(data['setback'], 'String');
            }
            if (data.hasOwnProperty('setback_code')) {
                obj['setback_code'] = ApiClient.convertToType(data['setback_code'], 'Number');
            }
            if (data.hasOwnProperty('setback_area')) {
                obj['setback_area'] = ApiClient.convertToType(data['setback_area'], 'Number');
            }
            if (data.hasOwnProperty('total_floor_area')) {
                obj['total_floor_area'] = ApiClient.convertToType(data['total_floor_area'], AreaWithMeasurementMethod);
            }
            if (data.hasOwnProperty('architectural_condition_flag')) {
                obj['architectural_condition_flag'] = ApiClient.convertToType(data['architectural_condition_flag'], 'Boolean');
            }
            if (data.hasOwnProperty('kenchiku_kakunin_number')) {
                obj['kenchiku_kakunin_number'] = ApiClient.convertToType(data['kenchiku_kakunin_number'], 'String');
            }
            if (data.hasOwnProperty('contractor')) {
                obj['contractor'] = ApiClient.convertToType(data['contractor'], 'String');
            }
            if (data.hasOwnProperty('completion_datejun')) {
                obj['completion_datejun'] = ApiClient.convertToType(data['completion_datejun'], DateJun);
            }
            if (data.hasOwnProperty('land_reclamation_datejun')) {
                obj['land_reclamation_datejun'] = ApiClient.convertToType(data['land_reclamation_datejun'], DateJun);
            }
            if (data.hasOwnProperty('structure')) {
                obj['structure'] = ApiClient.convertToType(data['structure'], 'String');
            }
            if (data.hasOwnProperty('structure_code')) {
                obj['structure_code'] = ApiClient.convertToType(data['structure_code'], 'Number');
            }
            if (data.hasOwnProperty('structure_note')) {
                obj['structure_note'] = ApiClient.convertToType(data['structure_note'], 'String');
            }
            if (data.hasOwnProperty('road_situation')) {
                obj['road_situation'] = ApiClient.convertToType(data['road_situation'], 'String');
            }
            if (data.hasOwnProperty('road_situation_code')) {
                obj['road_situation_code'] = ApiClient.convertToType(data['road_situation_code'], 'Number');
            }
            if (data.hasOwnProperty('hirayadate_flag')) {
                obj['hirayadate_flag'] = ApiClient.convertToType(data['hirayadate_flag'], 'Boolean');
            }
            if (data.hasOwnProperty('prefecture')) {
                obj['prefecture'] = ApiClient.convertToType(data['prefecture'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('town')) {
                obj['town'] = ApiClient.convertToType(data['town'], 'String');
            }
            if (data.hasOwnProperty('tyoume')) {
                obj['tyoume'] = ApiClient.convertToType(data['tyoume'], 'String');
            }
            if (data.hasOwnProperty('address_text')) {
                obj['address_text'] = ApiClient.convertToType(data['address_text'], 'String');
            }
            if (data.hasOwnProperty('branch_number_text')) {
                obj['branch_number_text'] = ApiClient.convertToType(data['branch_number_text'], 'String');
            }
            if (data.hasOwnProperty('zipcode_text')) {
                obj['zipcode_text'] = ApiClient.convertToType(data['zipcode_text'], 'String');
            }
            if (data.hasOwnProperty('jis_code_value')) {
                obj['jis_code_value'] = ApiClient.convertToType(data['jis_code_value'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('current_land_class')) {
                obj['current_land_class'] = ApiClient.convertToType(data['current_land_class'], 'String');
            }
            if (data.hasOwnProperty('current_land_class_code')) {
                obj['current_land_class_code'] = ApiClient.convertToType(data['current_land_class_code'], 'Number');
            }
            if (data.hasOwnProperty('registered_land_class')) {
                obj['registered_land_class'] = ApiClient.convertToType(data['registered_land_class'], 'String');
            }
            if (data.hasOwnProperty('topography')) {
                obj['topography'] = ApiClient.convertToType(data['topography'], 'String');
            }
            if (data.hasOwnProperty('topography_code')) {
                obj['topography_code'] = ApiClient.convertToType(data['topography_code'], 'Number');
            }
            if (data.hasOwnProperty('is_irregular_land_shape')) {
                obj['is_irregular_land_shape'] = ApiClient.convertToType(data['is_irregular_land_shape'], 'Boolean');
            }
            if (data.hasOwnProperty('land_situation')) {
                obj['land_situation'] = ApiClient.convertToType(data['land_situation'], 'String');
            }
            if (data.hasOwnProperty('land_situation_code')) {
                obj['land_situation_code'] = ApiClient.convertToType(data['land_situation_code'], 'Number');
            }
            if (data.hasOwnProperty('site_area')) {
                obj['site_area'] = ApiClient.convertToType(data['site_area'], AreaWithMeasurementMethod);
            }
            if (data.hasOwnProperty('coverage')) {
                obj['coverage'] = ApiClient.convertToType(data['coverage'], 'Number');
            }
            if (data.hasOwnProperty('floor_area_ratio')) {
                obj['floor_area_ratio'] = ApiClient.convertToType(data['floor_area_ratio'], 'Number');
            }
            if (data.hasOwnProperty('land_use_planning')) {
                obj['land_use_planning'] = ApiClient.convertToType(data['land_use_planning'], 'String');
            }
            if (data.hasOwnProperty('land_use_planning_code')) {
                obj['land_use_planning_code'] = ApiClient.convertToType(data['land_use_planning_code'], 'Number');
            }
            if (data.hasOwnProperty('private_road_area_public')) {
                obj['private_road_area_public'] = ApiClient.convertToType(data['private_road_area_public'], 'Number');
            }
            if (data.hasOwnProperty('private_road_area_measured')) {
                obj['private_road_area_measured'] = ApiClient.convertToType(data['private_road_area_measured'], 'Number');
            }
            if (data.hasOwnProperty('is_illegal_facing_road')) {
                obj['is_illegal_facing_road'] = ApiClient.convertToType(data['is_illegal_facing_road'], 'Boolean');
            }
            if (data.hasOwnProperty('private_road_rate_denom')) {
                obj['private_road_rate_denom'] = ApiClient.convertToType(data['private_road_rate_denom'], 'Number');
            }
            if (data.hasOwnProperty('private_road_rate_numer')) {
                obj['private_road_rate_numer'] = ApiClient.convertToType(data['private_road_rate_numer'], 'Number');
            }
            if (data.hasOwnProperty('manage_company_name')) {
                obj['manage_company_name'] = ApiClient.convertToType(data['manage_company_name'], 'String');
            }
            if (data.hasOwnProperty('manager_style')) {
                obj['manager_style'] = ApiClient.convertToType(data['manager_style'], 'String');
            }
            if (data.hasOwnProperty('manager_style_code')) {
                obj['manager_style_code'] = ApiClient.convertToType(data['manager_style_code'], 'Number');
            }
            if (data.hasOwnProperty('manage_company_tel_number')) {
                obj['manage_company_tel_number'] = ApiClient.convertToType(data['manage_company_tel_number'], 'String');
            }
            if (data.hasOwnProperty('manage_style')) {
                obj['manage_style'] = ApiClient.convertToType(data['manage_style'], 'String');
            }
            if (data.hasOwnProperty('manage_style_code')) {
                obj['manage_style_code'] = ApiClient.convertToType(data['manage_style_code'], 'Number');
            }
            if (data.hasOwnProperty('condominium_association_exist_flag')) {
                obj['condominium_association_exist_flag'] = ApiClient.convertToType(data['condominium_association_exist_flag'], 'Boolean');
            }
            if (data.hasOwnProperty('city_planning_area')) {
                obj['city_planning_area'] = ApiClient.convertToType(data['city_planning_area'], 'String');
            }
            if (data.hasOwnProperty('city_planning_area_code')) {
                obj['city_planning_area_code'] = ApiClient.convertToType(data['city_planning_area_code'], 'Number');
            }
            if (data.hasOwnProperty('development_number')) {
                obj['development_number'] = ApiClient.convertToType(data['development_number'], 'String');
            }
            if (data.hasOwnProperty('construction_method')) {
                obj['construction_method'] = ApiClient.convertToType(data['construction_method'], 'String');
            }
            if (data.hasOwnProperty('outer_wall')) {
                obj['outer_wall'] = ApiClient.convertToType(data['outer_wall'], 'String');
            }
            if (data.hasOwnProperty('use_district')) {
                obj['use_district'] = ApiClient.convertToType(data['use_district'], [UseDistrict]);
            }
            if (data.hasOwnProperty('building_feature')) {
                obj['building_feature'] = ApiClient.convertToType(data['building_feature'], [BuildingFeature]);
            }
            if (data.hasOwnProperty('facing_road')) {
                obj['facing_road'] = ApiClient.convertToType(data['facing_road'], [FacingRoad]);
            }
            if (data.hasOwnProperty('corner_lot')) {
                obj['corner_lot'] = ApiClient.convertToType(data['corner_lot'], 'String');
            }
            if (data.hasOwnProperty('corner_lot_code')) {
                obj['corner_lot_code'] = ApiClient.convertToType(data['corner_lot_code'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} building_guid
 */
Building.prototype['building_guid'] = undefined;

/**
 * @member {Date} modified
 */
Building.prototype['modified'] = undefined;

/**
 * @member {String} building_name
 */
Building.prototype['building_name'] = undefined;

/**
 * @member {String} building_furigana
 */
Building.prototype['building_furigana'] = undefined;

/**
 * @member {Number} total_units
 */
Building.prototype['total_units'] = undefined;

/**
 * @member {String} building_class
 */
Building.prototype['building_class'] = undefined;

/**
 * 1: 戸建<br/>2: 集合住宅<br/>3: 事務所・商業施設<br/>4: 土地<br/>5: 駐車場
 * @member {Number} building_class_code
 */
Building.prototype['building_class_code'] = undefined;

/**
 * @member {String} building_type
 */
Building.prototype['building_type'] = undefined;

/**
 * 1: マンション<br/>2: リゾートマンション<br/>3: アパート<br/>4: テラスハウス<br/>5: タウンハウス<br/>6: 戸建<br/>7: 土地<br/>8: 店舗<br/>9: 事務所<br/>10: ビル<br/>11: 倉庫<br/>12: 工場<br/>13: トランクルーム<br/>14: 駐車場<br/>15: バイク置き場<br/>16: その他
 * @member {Number} building_type_code
 */
Building.prototype['building_type_code'] = undefined;

/**
 * @member {Number} total_floors
 */
Building.prototype['total_floors'] = undefined;

/**
 * @member {Number} ground_floors
 */
Building.prototype['ground_floors'] = undefined;

/**
 * @member {Number} basement_floors
 */
Building.prototype['basement_floors'] = undefined;

/**
 * @member {String} setback
 */
Building.prototype['setback'] = undefined;

/**
 * 1: 不要<br/>2: 要<br/>3: 済
 * @member {Number} setback_code
 */
Building.prototype['setback_code'] = undefined;

/**
 * @member {Number} setback_area
 */
Building.prototype['setback_area'] = undefined;

/**
 * 延床面積 単位: 平方メートル 計測方法: 壁芯 内法 登記簿
 * @member {module:model/AreaWithMeasurementMethod} total_floor_area
 */
Building.prototype['total_floor_area'] = undefined;

/**
 * @member {Boolean} architectural_condition_flag
 */
Building.prototype['architectural_condition_flag'] = undefined;

/**
 * @member {String} kenchiku_kakunin_number
 */
Building.prototype['kenchiku_kakunin_number'] = undefined;

/**
 * @member {String} contractor
 */
Building.prototype['contractor'] = undefined;

/**
 * 竣工年月
 * @member {module:model/DateJun} completion_datejun
 */
Building.prototype['completion_datejun'] = undefined;

/**
 * 土地造成完了年月
 * @member {module:model/DateJun} land_reclamation_datejun
 */
Building.prototype['land_reclamation_datejun'] = undefined;

/**
 * @member {String} structure
 */
Building.prototype['structure'] = undefined;

/**
 * 1: 木造<br/>2: 軽量鉄骨<br/>3: 鉄筋コンクリート<br/>4: 鉄骨鉄筋コンクリート<br/>5: ALC<br/>6: プレキャストコンクリート<br/>7: 鉄筋ブロック<br/>8: 鉄骨プレ<br/>9: 鉄骨<br/>10: その他
 * @member {Number} structure_code
 */
Building.prototype['structure_code'] = undefined;

/**
 * @member {String} structure_note
 */
Building.prototype['structure_note'] = undefined;

/**
 * @member {String} road_situation
 */
Building.prototype['road_situation'] = undefined;

/**
 * 1: 一方<br/>2: 二方<br/>3: 三方<br/>4: 四方<br/>5: 角地
 * @member {Number} road_situation_code
 */
Building.prototype['road_situation_code'] = undefined;

/**
 * @member {Boolean} hirayadate_flag
 */
Building.prototype['hirayadate_flag'] = undefined;

/**
 * @member {String} prefecture
 */
Building.prototype['prefecture'] = undefined;

/**
 * @member {String} city
 */
Building.prototype['city'] = undefined;

/**
 * @member {String} town
 */
Building.prototype['town'] = undefined;

/**
 * @member {String} tyoume
 */
Building.prototype['tyoume'] = undefined;

/**
 * @member {String} address_text
 */
Building.prototype['address_text'] = undefined;

/**
 * @member {String} branch_number_text
 */
Building.prototype['branch_number_text'] = undefined;

/**
 * @member {String} zipcode_text
 */
Building.prototype['zipcode_text'] = undefined;

/**
 * @member {Number} jis_code_value
 */
Building.prototype['jis_code_value'] = undefined;

/**
 * @member {Number} latitude
 */
Building.prototype['latitude'] = undefined;

/**
 * @member {Number} longitude
 */
Building.prototype['longitude'] = undefined;

/**
 * @member {String} current_land_class
 */
Building.prototype['current_land_class'] = undefined;

/**
 * 1: 宅地<br/>2: 田<br/>3: 畑<br/>4: 山林<br/>5: 雑種地<br/>6: その他<br/>7: 塩田<br/>8: 境内地<br/>9: 原野<br/>10: 公園<br/>11: 公衆用道路<br/>12: 鉱泉地<br/>13: 水道用地<br/>14: 井溝<br/>15: ため池<br/>16: 池沼<br/>17: 堤<br/>18: 保安林<br/>19: 牧場<br/>20: 墓地<br/>21: 用悪水路<br/>22: 運河用地
 * @member {Number} current_land_class_code
 */
Building.prototype['current_land_class_code'] = undefined;

/**
 * @member {String} registered_land_class
 */
Building.prototype['registered_land_class'] = undefined;

/**
 * @member {String} topography
 */
Building.prototype['topography'] = undefined;

/**
 * 1: 平坦<br/>2: 高台<br/>3: 低地<br/>4: ひな段<br/>5: 傾斜地<br/>99: その他
 * @member {Number} topography_code
 */
Building.prototype['topography_code'] = undefined;

/**
 * @member {Boolean} is_irregular_land_shape
 */
Building.prototype['is_irregular_land_shape'] = undefined;

/**
 * @member {String} land_situation
 */
Building.prototype['land_situation'] = undefined;

/**
 * 1: 更地<br/>2: 古屋あり<br/>3: 造成済み<br/>4: 未造成
 * @member {Number} land_situation_code
 */
Building.prototype['land_situation_code'] = undefined;

/**
 * 土地面積 単位: 平方メートル 計測方法: 公簿 実測
 * @member {module:model/AreaWithMeasurementMethod} site_area
 */
Building.prototype['site_area'] = undefined;

/**
 * @member {Number} coverage
 */
Building.prototype['coverage'] = undefined;

/**
 * @member {Number} floor_area_ratio
 */
Building.prototype['floor_area_ratio'] = undefined;

/**
 * @member {String} land_use_planning
 */
Building.prototype['land_use_planning'] = undefined;

/**
 * 1: 不要<br/>2: 要<br/>3: 届出中<br/>4: 届出済
 * @member {Number} land_use_planning_code
 */
Building.prototype['land_use_planning_code'] = undefined;

/**
 * @member {Number} private_road_area_public
 */
Building.prototype['private_road_area_public'] = undefined;

/**
 * @member {Number} private_road_area_measured
 */
Building.prototype['private_road_area_measured'] = undefined;

/**
 * @member {Boolean} is_illegal_facing_road
 * @default false
 */
Building.prototype['is_illegal_facing_road'] = false;

/**
 * @member {Number} private_road_rate_denom
 */
Building.prototype['private_road_rate_denom'] = undefined;

/**
 * @member {Number} private_road_rate_numer
 */
Building.prototype['private_road_rate_numer'] = undefined;

/**
 * @member {String} manage_company_name
 */
Building.prototype['manage_company_name'] = undefined;

/**
 * @member {String} manager_style
 */
Building.prototype['manager_style'] = undefined;

/**
 * 1: 有<br/>2: 無<br/>3: 日勤<br/>4: 巡回<br/>5: 常駐
 * @member {Number} manager_style_code
 */
Building.prototype['manager_style_code'] = undefined;

/**
 * @member {String} manage_company_tel_number
 */
Building.prototype['manage_company_tel_number'] = undefined;

/**
 * @member {String} manage_style
 */
Building.prototype['manage_style'] = undefined;

/**
 * 1: 自主管理<br/>2: 一部委託<br/>3: 全部委託
 * @member {Number} manage_style_code
 */
Building.prototype['manage_style_code'] = undefined;

/**
 * @member {Boolean} condominium_association_exist_flag
 */
Building.prototype['condominium_association_exist_flag'] = undefined;

/**
 * @member {String} city_planning_area
 */
Building.prototype['city_planning_area'] = undefined;

/**
 * 1: 市街化区域<br/>2: 市街化調整区域<br/>3: 非線引き区域<br/>4: 域外<br/>5: 準都市計画区域
 * @member {Number} city_planning_area_code
 */
Building.prototype['city_planning_area_code'] = undefined;

/**
 * @member {String} development_number
 */
Building.prototype['development_number'] = undefined;

/**
 * @member {String} construction_method
 */
Building.prototype['construction_method'] = undefined;

/**
 * @member {String} outer_wall
 */
Building.prototype['outer_wall'] = undefined;

/**
 * @member {Array.<module:model/UseDistrict>} use_district
 */
Building.prototype['use_district'] = undefined;

/**
 * @member {Array.<module:model/BuildingFeature>} building_feature
 */
Building.prototype['building_feature'] = undefined;

/**
 * @member {Array.<module:model/FacingRoad>} facing_road
 */
Building.prototype['facing_road'] = undefined;

/**
 * @member {String} corner_lot
 */
Building.prototype['corner_lot'] = undefined;

/**
 * 1: 東南角地<br/>2: 南西角地<br/>3: 北東角地<br/>4: 北西角地<br/>5: 三方角地<br/>6: 四方角地
 * @member {Number} corner_lot_code
 */
Building.prototype['corner_lot_code'] = undefined;






export default Building;

