/**
 * ES 物件API
 * （株）いい生活 が提供予定の 物件情報API のインターフェイス仕様書  いい物件Oneに登録した賃貸物件情報を参照する物件参照API仕様について定める。  ※1: 開発中のため、実際のリリース時の仕様は異なる場合がございます。  ※2: 売買物件に関する仕様に関してはα版であり、今後大きな仕様の見直しを行う可能性がございます。  ## リソース仕様  ### 通信仕様  HTTP/2 および HTTP/1.1 をサポートする。通信はTLSで暗号化されたHTTPSのみを許可する。  ### リクエストヘッダ  リクエストヘッダには以下の指定を必須とする。  | No. | リクエストヘッダのフィールド名 | 指定値 | |:---:|:-------------------------------|:-------| | 1 | Accept | application/json | | 2 | X-Api-Key | 弊社が指定するキー。ご利用のお客様を特定するためのもの。 |  Acceptヘッダには、常にapplication/json を指定する。 これにより、レスポンスがJSONであることを指示する。  ### データフォーマットと文字コード  データフォーマットはJSON、文字コードはUTF-8とする。  ### データ型  通常のJSONの型以外に擬似型としていくつかのデータ型を用意している。 これは、JSON標準では表現しきれないデータや、不動産特有のデータを扱うために定義したもので使用する。 また、ここに記載の無いデータ型については、 OpenAPI Specification (Version 3.0.2) の DataTypes に準拠する。  * [DataTypes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types)   | No. | 型 | 説明 | |:---:|:---|:-----| | 1 | string | JSON標準の文字列 | | 2 | int | JSON標準の整数 | | 3 | float | JSON標準の浮動小数点数 | | 4 | bool | JSON標準の真偽値 | | 5 | datetime | ISO8611フォーマットの日付時刻を表す文字列。YYYY-MM-DDTHH:MM:SS。 <br> 例: 2015-08-26T19:16:03 = 2015年8月26日19時16分03秒 | | 6 | date | ISO8611フォーマットの日付を表す文字列。YYYY-MM-DD。 <br> 例: 2015-08-26 = 2015年8月26日 | | 7 | datejun | 後述 |  #### datejun型  いい生活独自の日付と旬を表すフォーマット。YYYYMMJDD。  * YYYY: 西暦年 * MM: 月。01～12。ただし00とすることにより、年単位までの精度の数字を表現可能。 * J: 旬。1=上旬、2=中旬、3=下旬。 0とすることで月単位までの精度の数字を表現可能。 * DD: 日。01～31。ただし00とすることにより、旬単位までの精度の数字を表現可能。日単位の精度の場合、1～10日までは旬を1、11～20日までは旬を2、21日以降は旬を3と指定する必要がある。 * 例:     * 201900000 = 2019年     * 201901000 = 2019年1月     * 201903100 = 2019年3月上旬     * 201912300 = 2019年12月下旬     * 201906105 = 2019年6月5日     * 201908216 = 2019年8月16日  ## 検索パラメータ  ### OR 検索  パラメータタイプが `array` のキーについては、クエリパラメータで複数指定を行った場合、 指定された値のいずれかに一致する対象を検索する（ OR 検索）。  ex) `?layout_type_code=1&layout_type_code=2`  ### ソート順  `*.order` という名前のパラメータでソート順を指定可能。ascを指定したとき昇順、descを指定したとき降順となる。  ex) `?price.order=desc`  基本的にソート順は一つだけ指定する。 
 *
 * The version of the OpenAPI document: 6.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EsApi);
  }
}(this, function(expect, EsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EsApi.RentPickupFeature();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RentPickupFeature', function() {
    it('should create an instance of RentPickupFeature', function() {
      // uncomment below and update the code to test RentPickupFeature
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be.a(EsApi.RentPickupFeature);
    });

    it('should have the property isFurnished (base name: "is_furnished")', function() {
      // uncomment below and update the code to test the property isFurnished
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasAppliances (base name: "has_appliances")', function() {
      // uncomment below and update the code to test the property hasAppliances
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isNetFree (base name: "is_net_free")', function() {
      // uncomment below and update the code to test the property isNetFree
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isOver2f (base name: "is_over_2f")', function() {
      // uncomment below and update the code to test the property isOver2f
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isBathToiletSeparate (base name: "is_bath_toilet_separate")', function() {
      // uncomment below and update the code to test the property isBathToiletSeparate
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasAircon (base name: "has_aircon")', function() {
      // uncomment below and update the code to test the property hasAircon
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasAutoLock (base name: "has_auto_lock")', function() {
      // uncomment below and update the code to test the property hasAutoLock
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasElevator (base name: "has_elevator")', function() {
      // uncomment below and update the code to test the property hasElevator
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasLandryRoom (base name: "has_landry_room")', function() {
      // uncomment below and update the code to test the property hasLandryRoom
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isFlooring (base name: "is_flooring")', function() {
      // uncomment below and update the code to test the property isFlooring
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isDesignersApartment (base name: "is_designers_apartment")', function() {
      // uncomment below and update the code to test the property isDesignersApartment
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isBarrierFree (base name: "is_barrier_free")', function() {
      // uncomment below and update the code to test the property isBarrierFree
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isSouthFacing (base name: "is_south_facing")', function() {
      // uncomment below and update the code to test the property isSouthFacing
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isHighestFloor (base name: "is_highest_floor")', function() {
      // uncomment below and update the code to test the property isHighestFloor
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isCornerRoom (base name: "is_corner_room")', function() {
      // uncomment below and update the code to test the property isCornerRoom
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasSystemKitchen (base name: "has_system_kitchen")', function() {
      // uncomment below and update the code to test the property hasSystemKitchen
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasIhStove (base name: "has_ih_stove")', function() {
      // uncomment below and update the code to test the property hasIhStove
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasGasStove (base name: "has_gas_stove")', function() {
      // uncomment below and update the code to test the property hasGasStove
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasMultipleGasStove (base name: "has_multiple_gas_stove")', function() {
      // uncomment below and update the code to test the property hasMultipleGasStove
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasReboilBath (base name: "has_reboil_bath")', function() {
      // uncomment below and update the code to test the property hasReboilBath
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasWashlet (base name: "has_washlet")', function() {
      // uncomment below and update the code to test the property hasWashlet
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasBathDryer (base name: "has_bath_dryer")', function() {
      // uncomment below and update the code to test the property hasBathDryer
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasFloorHeating (base name: "has_floor_heating")', function() {
      // uncomment below and update the code to test the property hasFloorHeating
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasCloset (base name: "has_closet")', function() {
      // uncomment below and update the code to test the property hasCloset
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasWalkInCloset (base name: "has_walk_in_closet")', function() {
      // uncomment below and update the code to test the property hasWalkInCloset
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasCatv (base name: "has_catv")', function() {
      // uncomment below and update the code to test the property hasCatv
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasCs (base name: "has_cs")', function() {
      // uncomment below and update the code to test the property hasCs
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasBs (base name: "has_bs")', function() {
      // uncomment below and update the code to test the property hasBs
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasOpticalFiber (base name: "has_optical_fiber")', function() {
      // uncomment below and update the code to test the property hasOpticalFiber
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isAllElectric (base name: "is_all_electric")', function() {
      // uncomment below and update the code to test the property isAllElectric
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasWashroom (base name: "has_washroom")', function() {
      // uncomment below and update the code to test the property hasWashroom
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property isNoBuildingInFront (base name: "is_no_building_in_front")', function() {
      // uncomment below and update the code to test the property isNoBuildingInFront
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

    it('should have the property hasVerandaBalcony (base name: "has_veranda_balcony")', function() {
      // uncomment below and update the code to test the property hasVerandaBalcony
      //var instane = new EsApi.RentPickupFeature();
      //expect(instance).to.be();
    });

  });

}));
