/**
 * ES 物件API
 * （株）いい生活 が提供予定の 物件情報API のインターフェイス仕様書  いい物件Oneに登録した賃貸物件情報を参照する物件参照API仕様について定める。  ※1: 開発中のため、実際のリリース時の仕様は異なる場合がございます。  ※2: 売買物件に関する仕様に関してはα版であり、今後大きな仕様の見直しを行う可能性がございます。  ## リソース仕様  ### 通信仕様  HTTP/2 および HTTP/1.1 をサポートする。通信はTLSで暗号化されたHTTPSのみを許可する。  ### リクエストヘッダ  リクエストヘッダには以下の指定を必須とする。  | No. | リクエストヘッダのフィールド名 | 指定値 | |:---:|:-------------------------------|:-------| | 1 | Accept | application/json | | 2 | X-Api-Key | 弊社が指定するキー。ご利用のお客様を特定するためのもの。 |  Acceptヘッダには、常にapplication/json を指定する。 これにより、レスポンスがJSONであることを指示する。  ### データフォーマットと文字コード  データフォーマットはJSON、文字コードはUTF-8とする。  ### データ型  通常のJSONの型以外に擬似型としていくつかのデータ型を用意している。 これは、JSON標準では表現しきれないデータや、不動産特有のデータを扱うために定義したもので使用する。 また、ここに記載の無いデータ型については、 OpenAPI Specification (Version 3.0.2) の DataTypes に準拠する。  * [DataTypes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types)   | No. | 型 | 説明 | |:---:|:---|:-----| | 1 | string | JSON標準の文字列 | | 2 | int | JSON標準の整数 | | 3 | float | JSON標準の浮動小数点数 | | 4 | bool | JSON標準の真偽値 | | 5 | datetime | ISO8611フォーマットの日付時刻を表す文字列。YYYY-MM-DDTHH:MM:SS。 <br> 例: 2015-08-26T19:16:03 = 2015年8月26日19時16分03秒 | | 6 | date | ISO8611フォーマットの日付を表す文字列。YYYY-MM-DD。 <br> 例: 2015-08-26 = 2015年8月26日 | | 7 | datejun | 後述 |  #### datejun型  いい生活独自の日付と旬を表すフォーマット。YYYYMMJDD。  * YYYY: 西暦年 * MM: 月。01～12。ただし00とすることにより、年単位までの精度の数字を表現可能。 * J: 旬。1=上旬、2=中旬、3=下旬。 0とすることで月単位までの精度の数字を表現可能。 * DD: 日。01～31。ただし00とすることにより、旬単位までの精度の数字を表現可能。日単位の精度の場合、1～10日までは旬を1、11～20日までは旬を2、21日以降は旬を3と指定する必要がある。 * 例:     * 201900000 = 2019年     * 201901000 = 2019年1月     * 201903100 = 2019年3月上旬     * 201912300 = 2019年12月下旬     * 201906105 = 2019年6月5日     * 201908216 = 2019年8月16日  ## 検索パラメータ  ### OR 検索  パラメータタイプが `array` のキーについては、クエリパラメータで複数指定を行った場合、 指定された値のいずれかに一致する対象を検索する（ OR 検索）。  ex) `?layout_type_code=1&layout_type_code=2`  ### ソート順  `*.order` という名前のパラメータでソート順を指定可能。ascを指定したとき昇順、descを指定したとき降順となる。  ex) `?price.order=desc`  基本的にソート順は一つだけ指定する。 
 *
 * The version of the OpenAPI document: 6.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Agent from './model/Agent';
import AgentList from './model/AgentList';
import AreaAggregateElem from './model/AreaAggregateElem';
import AreaAggregateResult from './model/AreaAggregateResult';
import AreaLevel from './model/AreaLevel';
import AreaWithMeasurementMethod from './model/AreaWithMeasurementMethod';
import Building from './model/Building';
import BuildingFeature from './model/BuildingFeature';
import BuildingList from './model/BuildingList';
import BuildingPreview from './model/BuildingPreview';
import BuildingPropertyList from './model/BuildingPropertyList';
import BuildingPropertyPreview from './model/BuildingPropertyPreview';
import BusStopAccess from './model/BusStopAccess';
import CarAccess from './model/CarAccess';
import DateJun from './model/DateJun';
import Deposit from './model/Deposit';
import DwellingUnit from './model/DwellingUnit';
import DwellingUnitFeature from './model/DwellingUnitFeature';
import DwellingUnitOuterFacility from './model/DwellingUnitOuterFacility';
import FacingRoad from './model/FacingRoad';
import FreeRent from './model/FreeRent';
import HTTPValidationError from './model/HTTPValidationError';
import Institution from './model/Institution';
import Insurance from './model/Insurance';
import IntRange from './model/IntRange';
import LineAggregateElem from './model/LineAggregateElem';
import LineAggregateResult from './model/LineAggregateResult';
import LineLevel from './model/LineLevel';
import Order from './model/Order';
import OtherInitialCost from './model/OtherInitialCost';
import OtherMonthlyCost from './model/OtherMonthlyCost';
import Price from './model/Price';
import PriceWithUnit from './model/PriceWithUnit';
import PropertyList from './model/PropertyList';
import PropertyParking from './model/PropertyParking';
import RenewalFee from './model/RenewalFee';
import RentBaitaiCode from './model/RentBaitaiCode';
import RentBrokerageAllocation from './model/RentBrokerageAllocation';
import RentContractCondition from './model/RentContractCondition';
import RentPeriod from './model/RentPeriod';
import RentPickupFeature from './model/RentPickupFeature';
import RentProperty from './model/RentProperty';
import RentPropertyPreview from './model/RentPropertyPreview';
import RentPropertyPreviewBase from './model/RentPropertyPreviewBase';
import RentReform from './model/RentReform';
import Room from './model/Room';
import SaleBaitaiCode from './model/SaleBaitaiCode';
import Staff from './model/Staff';
import Station from './model/Station';
import Tag from './model/Tag';
import TagDetail from './model/TagDetail';
import TagListResult from './model/TagListResult';
import Tokuyuchin from './model/Tokuyuchin';
import Transportation from './model/Transportation';
import UseDistrict from './model/UseDistrict';
import ValidationError from './model/ValidationError';
import ValueWithUnit from './model/ValueWithUnit';
import AgentQueryAPIApi from './api/AgentQueryAPIApi';
import BuildingQueryAPIApi from './api/BuildingQueryAPIApi';
import RentPropertyQueryAPIApi from './api/RentPropertyQueryAPIApi';
import TagQueryAPIApi from './api/TagQueryAPIApi';


/**
* __API_OneAPI1_2___HTTP_2__HTTP_1_1_TLSHTTPS___No________________________________________________________1___Accept___application_json____2___X_Api_Key_____Acceptapplication_json__JSON_JSONUTF_8_JSONJSON_OpenAPI_Specification__Version_3_0_2__DataTypes___DataTypes_https__github_com_OAI_OpenAPI_Specification_blob_master_versions_3_0_2_mddata_types__No__________________________1___string___JSON____2___int___JSON____3___float___JSON____4___bool___JSON____5___datetime___ISO8611YYYY_MM_DDTHHMMSS_br__2015_08_26T191603__2015826191603____6___date___ISO8611YYYY_MM_DD_br__2015_08_26__2015826____7___datejun______datejunYYYYMMJDD_YYYY__MM_011200_J_123_0_DD_013100110111202213______201900000__2019_____201901000__20191_____201903100__20193_____201912300__201912_____201906105__201965_____201908216__2019816__OR__array__OR_ex_layout_type_code1layout_type_code2__order_ascdescex_price_orderdesc.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EsApi = require('index'); // See note below*.
* var xxxSvc = new EsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 6.1.3
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Agent model constructor.
     * @property {module:model/Agent}
     */
    Agent,

    /**
     * The AgentList model constructor.
     * @property {module:model/AgentList}
     */
    AgentList,

    /**
     * The AreaAggregateElem model constructor.
     * @property {module:model/AreaAggregateElem}
     */
    AreaAggregateElem,

    /**
     * The AreaAggregateResult model constructor.
     * @property {module:model/AreaAggregateResult}
     */
    AreaAggregateResult,

    /**
     * The AreaLevel model constructor.
     * @property {module:model/AreaLevel}
     */
    AreaLevel,

    /**
     * The AreaWithMeasurementMethod model constructor.
     * @property {module:model/AreaWithMeasurementMethod}
     */
    AreaWithMeasurementMethod,

    /**
     * The Building model constructor.
     * @property {module:model/Building}
     */
    Building,

    /**
     * The BuildingFeature model constructor.
     * @property {module:model/BuildingFeature}
     */
    BuildingFeature,

    /**
     * The BuildingList model constructor.
     * @property {module:model/BuildingList}
     */
    BuildingList,

    /**
     * The BuildingPreview model constructor.
     * @property {module:model/BuildingPreview}
     */
    BuildingPreview,

    /**
     * The BuildingPropertyList model constructor.
     * @property {module:model/BuildingPropertyList}
     */
    BuildingPropertyList,

    /**
     * The BuildingPropertyPreview model constructor.
     * @property {module:model/BuildingPropertyPreview}
     */
    BuildingPropertyPreview,

    /**
     * The BusStopAccess model constructor.
     * @property {module:model/BusStopAccess}
     */
    BusStopAccess,

    /**
     * The CarAccess model constructor.
     * @property {module:model/CarAccess}
     */
    CarAccess,

    /**
     * The DateJun model constructor.
     * @property {module:model/DateJun}
     */
    DateJun,

    /**
     * The Deposit model constructor.
     * @property {module:model/Deposit}
     */
    Deposit,

    /**
     * The DwellingUnit model constructor.
     * @property {module:model/DwellingUnit}
     */
    DwellingUnit,

    /**
     * The DwellingUnitFeature model constructor.
     * @property {module:model/DwellingUnitFeature}
     */
    DwellingUnitFeature,

    /**
     * The DwellingUnitOuterFacility model constructor.
     * @property {module:model/DwellingUnitOuterFacility}
     */
    DwellingUnitOuterFacility,

    /**
     * The FacingRoad model constructor.
     * @property {module:model/FacingRoad}
     */
    FacingRoad,

    /**
     * The FreeRent model constructor.
     * @property {module:model/FreeRent}
     */
    FreeRent,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The Institution model constructor.
     * @property {module:model/Institution}
     */
    Institution,

    /**
     * The Insurance model constructor.
     * @property {module:model/Insurance}
     */
    Insurance,

    /**
     * The IntRange model constructor.
     * @property {module:model/IntRange}
     */
    IntRange,

    /**
     * The LineAggregateElem model constructor.
     * @property {module:model/LineAggregateElem}
     */
    LineAggregateElem,

    /**
     * The LineAggregateResult model constructor.
     * @property {module:model/LineAggregateResult}
     */
    LineAggregateResult,

    /**
     * The LineLevel model constructor.
     * @property {module:model/LineLevel}
     */
    LineLevel,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The OtherInitialCost model constructor.
     * @property {module:model/OtherInitialCost}
     */
    OtherInitialCost,

    /**
     * The OtherMonthlyCost model constructor.
     * @property {module:model/OtherMonthlyCost}
     */
    OtherMonthlyCost,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The PriceWithUnit model constructor.
     * @property {module:model/PriceWithUnit}
     */
    PriceWithUnit,

    /**
     * The PropertyList model constructor.
     * @property {module:model/PropertyList}
     */
    PropertyList,

    /**
     * The PropertyParking model constructor.
     * @property {module:model/PropertyParking}
     */
    PropertyParking,

    /**
     * The RenewalFee model constructor.
     * @property {module:model/RenewalFee}
     */
    RenewalFee,

    /**
     * The RentBaitaiCode model constructor.
     * @property {module:model/RentBaitaiCode}
     */
    RentBaitaiCode,

    /**
     * The RentBrokerageAllocation model constructor.
     * @property {module:model/RentBrokerageAllocation}
     */
    RentBrokerageAllocation,

    /**
     * The RentContractCondition model constructor.
     * @property {module:model/RentContractCondition}
     */
    RentContractCondition,

    /**
     * The RentPeriod model constructor.
     * @property {module:model/RentPeriod}
     */
    RentPeriod,

    /**
     * The RentPickupFeature model constructor.
     * @property {module:model/RentPickupFeature}
     */
    RentPickupFeature,

    /**
     * The RentProperty model constructor.
     * @property {module:model/RentProperty}
     */
    RentProperty,

    /**
     * The RentPropertyPreview model constructor.
     * @property {module:model/RentPropertyPreview}
     */
    RentPropertyPreview,

    /**
     * The RentPropertyPreviewBase model constructor.
     * @property {module:model/RentPropertyPreviewBase}
     */
    RentPropertyPreviewBase,

    /**
     * The RentReform model constructor.
     * @property {module:model/RentReform}
     */
    RentReform,

    /**
     * The Room model constructor.
     * @property {module:model/Room}
     */
    Room,

    /**
     * The SaleBaitaiCode model constructor.
     * @property {module:model/SaleBaitaiCode}
     */
    SaleBaitaiCode,

    /**
     * The Staff model constructor.
     * @property {module:model/Staff}
     */
    Staff,

    /**
     * The Station model constructor.
     * @property {module:model/Station}
     */
    Station,

    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag,

    /**
     * The TagDetail model constructor.
     * @property {module:model/TagDetail}
     */
    TagDetail,

    /**
     * The TagListResult model constructor.
     * @property {module:model/TagListResult}
     */
    TagListResult,

    /**
     * The Tokuyuchin model constructor.
     * @property {module:model/Tokuyuchin}
     */
    Tokuyuchin,

    /**
     * The Transportation model constructor.
     * @property {module:model/Transportation}
     */
    Transportation,

    /**
     * The UseDistrict model constructor.
     * @property {module:model/UseDistrict}
     */
    UseDistrict,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
     * The ValueWithUnit model constructor.
     * @property {module:model/ValueWithUnit}
     */
    ValueWithUnit,

    /**
    * The AgentQueryAPIApi service constructor.
    * @property {module:api/AgentQueryAPIApi}
    */
    AgentQueryAPIApi,

    /**
    * The BuildingQueryAPIApi service constructor.
    * @property {module:api/BuildingQueryAPIApi}
    */
    BuildingQueryAPIApi,

    /**
    * The RentPropertyQueryAPIApi service constructor.
    * @property {module:api/RentPropertyQueryAPIApi}
    */
    RentPropertyQueryAPIApi,

    /**
    * The TagQueryAPIApi service constructor.
    * @property {module:api/TagQueryAPIApi}
    */
    TagQueryAPIApi
};
